name: Elsewhere
favicon: null
layout_spectrum: 0.8135674751829356
typography_spectrum: 0.44701847061514854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7460754686035216
  lightness: 0.6430553935933858
  saturation: 0.41744970227591693
  rhythmicContrast: 0.5244160727597773
purpose: []
